# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: omalperera-github-io
google_analytics: UA-110155922-1
title: Omal Perera


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Omal Perera

description: Omal Perera
author:
  name: Omal Perera
  email: omalperera8@gmail.com
  github: OmalPerera
  twitter: OmalPerera
  pinterest:
  linkedin: OmalPerera
  bio: Information Systems undergraduate at Sabaragamuwa University of Sri Lanka</br>Full Stack Developer</br>Trainee Software Engineer at 99X Technologies.
  email_md5: f29579eebcf0cb079c43eb37c7123235


rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

 # Settings for comments helper
# Set 'provider' to the comment provider you want to use.
# Set 'provider' to false to turn commenting off globally.
#
comments :
  provider : disqus
  disqus :
    short_name : omalperera-github-io
  livefyre :
    site_id :
  intensedebate :
    account :
  facebook :
    appid :
    num_posts:
    width:
    colorscheme:


  # Settings for analytics helper
  # Set 'provider' to the analytics provider you want to use.
  # Set 'provider' to false to turn analytics off globally.
  #
  analytics :
    provider : googleUA
    google :
        tracking_id :
    googleUA :
        tracking_id : 'UA-110155922-1'
        property_name : 'omalperera.github.io'
    getclicky :
      site_id :
    mixpanel :
        token :
    piwik :
        baseURL : # Piwik installation address (without protocol)
        idsite :                   # the id of the site on Piwik

url: https://omalperera.github.io

plugins :
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
